---
title: "Animal Crossing"
author: "Albert Kenji"
date: "07/08/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Animal Crossing - TidyTuesday (2020-05-05)

Source:  VillagerDB|Metacritic

```{r library}

library(tidyverse)
library(tidytuesdayR)

```


```{r datasets}

theme_set(theme_minimal())

tuesdata <- tidytuesdayR::tt_load('2020-05-05')

critic <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/critic.tsv')

user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')

items <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/items.csv')

villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')

```

```{r view-datasets}

villagers %>% 
  head() %>% 
  View()

items %>% 
  head() %>% 
  View()


```

## Text Analysis

```{r text-analysis}

critic %>% 
  head() %>% 
  View()

user_reviews %>% 
  head() %>% 
  View()

critic %>% 
  ggplot(aes(grade)) +
  geom_histogram()

user_reviews %>% 
  ggplot(aes(grade)) +
  geom_histogram()

head(user_reviews$text)

```


```{r tidytext}

library(tidytext)

user_reviews %>% 
  group_by(week = lubridate::floor_date(date, "week")) %>% 
  summarise(nb_reviews = n(),
            avg_grade = mean(grade))

user_review_words <- 
  user_reviews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word") %>% 
  count(user_name, date, grade, word)

```


```{r graph-user-review}

library(lubridate)

by_week <- 
  user_reviews %>% 
  group_by(week = floor_date(date, "week", week_start = 1)) %>% 
  summarise(nb_reviews = n(),
            avg_grade = mean(grade),
            pct_zero = mean(grade == 0),
            pct_ten = mean(grade == 10))

by_week %>% 
  ggplot(aes(week, avg_grade)) +
  geom_line() +
  geom_point(aes(size = nb_reviews)) +
  expand_limits(y = 0) +
  labs(x = "Time",
       y = "Avarage Grade",
       size = "# of reviews")

user_reviews %>% 
  ggplot(aes(grade)) +
  geom_histogram() +
  labs(title = "Most reviews are very low or very high")

by_week %>% 
  gather(type, value, contains("pct")) %>% 
  mutate(type = ifelse(type == "pct_zero", "% rated 0", "% rated 10")) %>% 
  ggplot(aes(week, value, color = type)) +
  geom_line() +
  geom_vline(xintercept = as.Date(c("2020-04-01", "2020-04-12")),
             lty = 2) +
  geom_point(aes(size = nb_reviews)) +
  scale_y_continuous(labels = scales::percent) +
  expand_limits(y = 0) +
  labs(x = "Time",
       y = "% of reviews",
       size = "Total Reviews in week",
       title = "Reviews got more polarizing in middle of game")

```


```{r by-word 1}

by_word <- 
  user_review_words %>% 
  group_by(word) %>% 
  summarize(avg_grade = mean(grade),
            nb_reviews = n()) %>% 
  arrange(desc(nb_reviews)) %>% 
  filter(nb_reviews >= 75) %>% 
  arrange(desc(avg_grade))

by_word %>% 
  ggplot(aes(nb_reviews, avg_grade)) +
  geom_point() +
  geom_text(aes(label = word), vjust = 1, hjust = 1, check_overlap = TRUE) + 
  scale_x_log10()

```

```{r by-word 2}

by_word %>% 
  top_n(20, -avg_grade) %>% 
  ggplot(aes(nb_reviews, avg_grade)) +
  geom_point() +
  geom_text(aes(label = word), vjust = 1, hjust = 1, check_overlap = TRUE) + 
  scale_x_log10() +
  labs(title = "What words are associated with low-grade reviews",
       subtitle = "20 most negative words; only words in at least 75 reviews")

```

```{r model stm}

library(widyr)
library(stm)

review_matrix <- 
user_review_words %>% 
  group_by(word) %>% 
  filter(n() >= 25) %>% 
  cast_sparse(user_name, word, n)

topic_model <- stm(review_matrix, 
                   K = 4, verbose = TRUE, init.type = "Spectral")

```

```{r model-results stm}

tidy(topic_model) %>% 
  group_by(topic) %>% 
  top_n(6, beta) %>% 
  mutate(term = reorder_within(term, beta, topic)) %>% 
  ggplot(aes(beta, term)) +
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~topic, scales = "free_y")

```

## Sentimental Analysis with Tidymodels

```{r tidymodels}

# Library

library(tidyverse)
library(tidymodels)
library(tidytext)
library(textrecipes)

# Dataset

user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')

user_reviews

# EDA

user_reviews %>% 
  count(grade) %>% 
  ggplot(aes(grade, n)) + 
  geom_col()

user_reviews %>% 
  filter(grade > 8) %>% 
  sample_n(5) %>% 
  pull(text)


reviews_parsed <- 
  user_reviews %>% 
  mutate(text = str_remove(text, "Expand$"),
         rating = case_when(grade > 6 ~ "Good",
                            TRUE ~ "Bad"))

words_per_review <- 
  reviews_parsed %>% 
  unnest_tokens(word, text) %>% 
  count(user_name, name = "total_words")

words_per_review %>% 
  ggplot(aes(total_words)) +
  geom_histogram()

# Build a Model  

set.seed(123)

## Train and Test Split - RSample

review_split <- initial_split(reviews_parsed, strata = rating)
review_train <- training(review_split)
review_test <- testing(review_split)

## Recipe - Recipes

review_rec <- 
  recipe(rating ~ text, data = review_train) %>% 
  textrecipes::step_tokenize(text) %>% 
  textrecipes::step_stopwords(text) %>% 
  textrecipes::step_tokenfilter(text, max_tokens = 500) %>% 
  textrecipes::step_tfidf(text) %>% 
  step_normalize(all_predictors())
  
review_prep <- 
  prep(review_rec)

## Choice models - Parsnip

lasso_spec <- logistic_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

# Join recipe and model - Workflows

lasso_wf <- 
  workflow() %>% 
  add_recipe(review_rec) %>% 
  add_model(lasso_spec)
  
# Tune Model Parameters - Dials

lambda_grid <- grid_regular(penalty(), levels = 30)
lambda_grid

review_folds <- bootstraps(review_train, strata = rating)
review_folds

doParallel::registerDoParallel()

set.seed(2020)

lasso_grid <- tune_grid(
  lasso_wf, 
  resamples = review_folds,
  grid = lambda_grid,
  metrics = metric_set(roc_auc, ppv, npv)
)

lasso_grid %>% 
  collect_metrics() %>% 
  ggplot(aes(penalty, mean, color = .metric)) +
  geom_line(size = 1.5, show.legend = FALSE) +
  facet_wrap(~.metric) +
  scale_x_log10()

# Choice model  

best_auc <- lasso_grid %>% 
  select_best("roc_auc")

final_lasso <- finalize_workflow(lasso_wf, best_auc)
final_lasso

# Exploring final model

library(vip)

final_lasso %>% 
  fit(review_train) %>% 
  pull_workflow_fit() %>% 
  vi(lambda = best_auc$penalty) %>% 
  group_by(Sign) %>% 
  top_n(20, wt = abs(Importance)) %>% 
  ungroup() %>% 
  mutate(Importance = abs(Importance),
         Variable = str_remove(Variable, "tfidf_text_"),
         Variable = fct_reorder(Variable, Importance)) %>% 
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~Sign, scales = "free_y")

review_final <- last_fit(final_lasso, review_split)

review_final %>% 
  collect_metrics()

review_final %>% 
  collect_predictions() %>% 
  conf_mat(rating, .pred_class)

```


## References

- David Robinson Tidy Tuesday live screencast Analyzing Animal Crossing in R.  

- Julia Silge: Sentiment analysis with tidymodels for Animal Crossing user reviews


