---
title: 'Avatar: The last airbender'
author: "Albert Kenji"
date: "11/08/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r dataset}

tt <- tidytuesdayR::tt_load("2020-08-11")
tt

avatar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv')

scene_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/scene_description.csv')


```

- Color pallete: tvthemes

```{r eda}

library(tidyverse)
library(tidytext)

avatar %>% 
  skimr::skim()

avatar %>% 
  head() %>% 
  View()

# Count
avatar %>% 
  group_by(book, book_num) %>% 
  count(book, sort = TRUE)

avatar %>% 
  group_by(chapter) %>% 
  count(chapter, sort = TRUE)

avatar %>% 
  group_by(director) %>% 
  count(director, writer, sort = TRUE)

avatar %>% 
  group_by(character) %>% 
  count(character, sort = TRUE)

avatar %>% 
  select(book, chapter_num, imdb_rating) %>% 
  ggplot(aes(x = chapter_num, y = imdb_rating)) +
  geom_point() +
  facet_wrap(~ book)

avatar %>% 
  ggplot(aes(imdb_rating)) +
  geom_histogram()

scene_description %>% 
  head() %>% 
  View()


```


```{r sentimental analysis}

# Library

library(tidyverse)
library(tidytext)
library(tidyr)
library(tvthemes)
library(extrafont)

# Datset
scene_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/scene_description.csv')

loadfonts()
import_avatar()

# Tidy Data
tidy_scene_descripition <- 
  scene_description %>% 
  unnest_tokens(word, scene_description) %>% 
  anti_join(stop_words)

tidy_scene_descripition %>%
  count(word, sort = TRUE) %>%
  filter(n > 200) %>%
  mutate(word = reorder(word, n))

bing_word_counts <- tidy_scene_descripition %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup() %>% 
  mutate()

bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n))

# Plot

bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(sentiment = str_to_upper(sentiment),
         word = str_to_title(word),
         word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  scale_color_avatar(palette = "EarthKingdom") +
  labs(title = "Most common negative and positive words",
       subtitle = "Avatar: The last airbender - Scene Description",
       y = NULL,
       x = NULL,
       caption = "Source: Appa|Graphic: Kenji") +
  coord_flip() +
  theme_avatar(title.font = "Slayer",
               text.font = "Slayer") +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, 
                              vjust = 0.5, 
                              size = 16, 
                              face = "bold", 
                              margin = margin (0,0,20,0),
                              color = "#3c3c44"),
    plot.subtitle = element_text(hjust = 0.5, 
                              vjust = 0.5, 
                              size = 14, 
                              face = "bold", 
                              margin = margin (0,0,20,0),
                              color = "#3c3c44"),
    axis.text = element_text(size = 14,
                              color = "#3c3c44"),
    legend.text = element_text(size = 12,
                               color = "#3c3c44"),
    legend.title = element_blank(),
    legend.position = c(0.90, 0.70),
    strip.text.x = element_text(size = 14,
                                face = "bold",
                                color = "#3c3c44")
  ) +
  ggsave("avatar.png", dpi = 320, width = 12, height = 7)


```

```{r wordcloud}

library(tidyverse)
library(wordcloud2)

# Clean up full_text variable
avatar <- avatar %>%
  mutate(full_text = str_replace_all(full_text,
                                     "[\\[\\]!.?,;'\"\\(\\)0-9]", 
                                     ""))

# Get wordcloud ready.
# Also remove "boring" words ;)
words <- tibble(
  word = unlist(str_split(avatar$full_text, pattern = " "))
) %>%
  mutate(
    word = tolower(word),
    word = trimws(word)
  ) %>%
  count(word) %>%
  rename(freq = n) %>%
  filter(!word %in% c("a", 
                      "and",
                      "but",
                      "or",
                      "the",
                      "of",
                      "to",
                      "you",
                      "me",
                      "she",
                      "her",
                      "hers",
                      "he",
                      "his",
                      "him",
                      "at",
                      "as",
                      "is",
                      "it",
                      "in",
                      "i",
                      "on",
                      "",
                      "\t",
                      "-",
                      "--")) %>%
  arrange(desc(freq))


# Standard wordcloud
wordcloud2(words,
           size = 1.5,
           backgroundColor = "#282a36",
           color = rep(c("#ff79c6",
                         "#8be9fd",
                         "#f8f8f2",
                         "#bd93f9",
                         "#6272a4"),
                       nrow(words)),
           shuffle = FALSE,
           rotateRatio = 0.25)

```

```{r julia_silge_ex}

# https://juliasilge.com/blog/last-airbender/

library(tvthemes)
library(tidytext)
library(extrafont)
library(tidylo)

loadfonts()
import_avatar()

avatar %>%
  filter(!is.na(character_words)) %>%
  mutate(
    book = fct_inorder(book),
    character = fct_lump_n(character, 10)
  ) %>%
  count(book, character) %>%
  mutate(character = reorder_within(character, n, book)) %>%
  ggplot(aes(n, character, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, scales = "free") +
  scale_y_reordered() +
  scale_fill_manual(values = c(
    avatar_pal("WaterTribe")(1),
    avatar_pal("EarthKingdom")(1),
    avatar_pal("FireNation")(1)
  )) +
  labs(y = NULL)

avatar_tidy <- avatar %>%
  filter(!is.na(character_words)) %>%
  mutate(aang = if_else(character == "Aang", "Aang", "Other")) %>%
  select(aang, book, text = character_words)

avatar_tidy %>%
  filter(aang == "Aang") %>%
  sample_n(10) %>%
  pull(text)

avatar_lo <- avatar_tidy %>%
  unnest_tokens(word, text) %>%
  count(aang, word) %>%
  bind_log_odds(aang, word, n) %>%
  arrange(-log_odds_weighted)

avatar_lo %>%
  group_by(aang) %>%
  top_n(15) %>%
  ungroup() %>%
  mutate(word = reorder(word, log_odds_weighted)) %>%
  ggplot(aes(log_odds_weighted, word, fill = aang)) +
  geom_col(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~aang, scales = "free") +
  scale_fill_avatar(palette = "AirNomads") +
  labs(y = NULL)

library(textfeatures)

tf <- textfeatures(
  avatar_tidy,
  sentiment = FALSE, word_dims = 0,
  normalize = FALSE, verbose = FALSE
)

tf %>%
  bind_cols(avatar_tidy) %>%
  group_by(aang) %>%
  summarise(across(starts_with("n_"), mean)) %>%
  pivot_longer(starts_with("n_"), names_to = "text_feature") %>%
  filter(value > 0.01) %>%
  mutate(text_feature = fct_reorder(text_feature, -value)) %>%
  ggplot(aes(aang, value, fill = aang)) +
  geom_col(position = "dodge", alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~text_feature, scales = "free", ncol = 6) +
  scale_fill_avatar("AirNomads") +
  labs(x = NULL, y = "Mean text features per spoken line")

## Model  

library(tidymodels)
library(textrecipes)
library(themis)

# Train and Test Split
set.seed(123)
avatar_split <- initial_split(avatar_tidy, strata = aang)
avatar_train <- training(avatar_split)
avatar_test <- testing(avatar_split)

# Cross Validation Folds
set.seed(234)
avatar_folds <- vfold_cv(avatar_train, strata = aang)
avatar_folds

# Recipes

avatar_rec <- recipe(aang ~ text, data = avatar_train) %>%
  step_downsample(aang) %>%
  step_textfeature(text) %>%
  step_zv(all_predictors()) %>%
  step_normalize(all_predictors())

avatar_prep <- prep(avatar_rec)
avatar_prep

juice(avatar_prep)

# Model Choice  

rf_spec <- rand_forest(trees = 1000) %>%
  set_engine("ranger") %>%
  set_mode("classification")

svm_spec <- svm_rbf(cost = 0.5) %>%
  set_engine("kernlab") %>%
  set_mode("classification")

# Workflow
avatar_wf <- workflow() %>%
  add_recipe(avatar_rec)

avatar_wf

doParallel::registerDoParallel()

# Random Forest
set.seed(1234)
rf_rs <- avatar_wf %>%
  add_model(rf_spec) %>%
  fit_resamples(
    resamples = avatar_folds,
    metrics = metric_set(roc_auc, accuracy, sens, spec),
    control = control_grid(save_pred = TRUE)
  )

# SVM
set.seed(2345)
svm_rs <- avatar_wf %>%
  add_model(svm_spec) %>%
  fit_resamples(
    resamples = avatar_folds,
    metrics = metric_set(roc_auc, accuracy, sens, spec),
    control = control_grid(save_pred = TRUE)
  )

## Evaluate model

collect_metrics(rf_rs)
conf_mat_resampled(rf_rs)
collect_metrics(svm_rs)
conf_mat_resampled(svm_rs)

svm_rs %>%
  collect_predictions() %>%
  group_by(id) %>%
  roc_curve(aang, .pred_Aang) %>%
  ggplot(aes(1 - specificity, sensitivity, color = id)) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_path(show.legend = FALSE, alpha = 0.6, size = 1.2) +
  scale_color_avatar(palette = "EarthKingdom") +
  coord_equal()

# Choice SVM  

library(vip)

set.seed(345)
avatar_imp <- avatar_wf %>%
  add_model(svm_spec) %>%
  fit(avatar_train) %>%
  pull_workflow_fit() %>%
  vi(
    method = "permute", nsim = 10,
    target = "aang", metric = "auc", reference_class = "Other",
    pred_wrapper = kernlab::predict, train = juice(avatar_prep)
  )

avatar_imp %>%
  slice_max(Importance, n = 8) %>%
  mutate(
    Variable = str_remove(Variable, "textfeature_text_n_"),
    Variable = fct_reorder(Variable, Importance)
  ) %>%
  ggplot(aes(Importance, Variable, color = Variable)) +
  geom_errorbar(aes(xmin = Importance - StDev, xmax = Importance + StDev),
    alpha = 0.5, size = 1.3
  ) +
  geom_point(size = 3) +
  theme(legend.position = "none") +
  scale_color_avatar(palette = "FireNation") +
  labs(y = NULL)

# Final Model
avatar_final <- avatar_wf %>%
  add_model(svm_spec) %>%
  last_fit(avatar_split)

avatar_final %>%
  collect_metrics()

avatar_final %>%
  collect_predictions() %>%
  conf_mat(aang, .pred_class)

```
 
 